### ISSUE TITLE
Develop Website

### ISSUE THREAD

**Issue by ernstsh** [ernstsh/CS361#11]
As a software developer, I need a user friendly website to display all of the information for my user. Set up domain for the website.
Implement HTML basics for each required page and decide on site layout.
Implement page style and layout.
“Connect” the visible website with our software through JavaScript/PHP/whatever.

**Comment by ernstsh** [comment]
To Do: add sources, finish adding initial data on categories of recyclables and recycling numbers

General website is set up. Accessible at  http://web.engr.oregonstate.edu/~ernstsh/

**Comment by ernstsh** [comment]
Sources to be added http://archive.grrn.org/zerowaste/twelve_categories.html for categories and http://naturalsociety.com/recycling-symbols-numbers-plastic-bottles-meaning/ for numbers

**Comment by mckennajones** [comment]
Here's a list of potentials images to use for the website: 
1. http://s3.amazonaws.com/bvsystem_tmp/pages/55/original/architectural-salvage.jpg?1313685657
2. http://www.honduras.com/wp-content/uploads/2012/05/newspaper.jpg
3. http://webuyscrapaz.com/wp-content/uploads/2012/10/scrapmetal-scottsdale-az.jpg
4. http://www.doyourpart.com/wp-content/uploads/2010/09/glass-bottles.jpg
5. http://madewithlovebyhannah.com/WordPress/photos/vintagefabricpieces.jpg
6. http://cf.ltkcdn.net/greenliving/images/std/85323-425x281-PlasticBottles.jpg
7. http://map.3dmodelfree.com/imguploads/Image/1106/map/2012/12/12-3.jpg
8. https://zeroresource.files.wordpress.com/2011/03/wikimedia-commons_400px-food_scraps_and_yard_debris_collection_in_portland_2010_by_tim_jewett_2011-03-29.jpg
9. http://www.woodworkideas.net/wp-content/uploads/2012/07/woodworking-scrap-wood.jpg
10. http://www.packer2000.com/images/Residential/bricks.jpg
11. https://timeglobalspin.files.wordpress.com/2012/12/int-soil-1213.jpg?w=480&h=320&crop=1
12. http://acsoriental.com/wp-content/uploads/2015/09/Chemicals.jpg

Stock images for each category of recyclables.
