### ISSUE TITLE
Find out where to dispose

### ISSUE THREAD

**Issue by ernstsh** [ernstsh/CS361#4]
As a software user, I want to view where I should dispose of a given item, so I can properly dispose of it.
Add disposal information field to the database of items
Display disposal information on item info page

**Comment by GabeM** [comment]
Disposal information has been added to the database. It is in the same table as Types, since disposal methods are related to what type of object it is.

**Comment by mckennajones** [comment]
This information was used to show the local landfills: http://www.yellowpages.com/corvallis-or/landfill-hours
