### ISSUE TITLE
Recyclable or not

### ISSUE THREAD

**Issue by ernstsh** [ernstsh/CS361#5]
As a software user, I want to view whether or not an item is recyclable, so I can properly dispose of it. Add recyclability field to database of items
Display recyclability info on item info page

**Comment by GabeM** [comment]
The Recyclable field has been added to the Items table of the database which will keep track of whther or not an item is recyclable.

**Comment by mckennajones** [comment]
This website was used to determine what can and cannot be recycled: http://www.buffalo.edu/recycling/recyclable.html
